import type { CountdownContent } from "./schema";

/**
 * The public walkthrough. There is deliberately **no** `startDate`: a demo whose
 * doors were mostly locked would show a visitor almost nothing, so here every
 * door is open and the calendar reads as a finished object.
 */
export const countdownGiftDemo: CountdownContent = {
  skin: "midnight",
  doorStyle: "envelope",
  title: "Twelve days until you're home",
  occasion: "the 14th",
  dedication: "One a day. I'm not telling you what's in any of them.",
  startDate: "",
  musicUrl: "",
  finaleTitle: "You waited twelve days.",
  finaleNote:
    "Every door you opened, all in one place — so you can go back to any of them whenever you want.",
  days: [
    {
      id: "d-1",
      kind: "letter",
      title: "Day one",
      text:
        "I made you something that takes twelve days.\nThat's on purpose.\n\nI kept thinking about how you're always the one who waits — for me, for the train, for news. So this time the waiting is the present, and there's something behind every day of it.\n\nSee you on the 14th.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-2",
      kind: "photo",
      title: "The morning we missed the ferry",
      text: "You laughed for a full minute. I was furious. You were right.",
      imageUrl: "https://images.pexels.com/photos/1252869/pexels-photo-1252869.jpeg?auto=compress&cs=tinysrgb&w=900",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-3",
      kind: "quote",
      title: "",
      text: "How lucky I am to have something that makes saying goodbye so hard.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "A. A. Milne",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-4",
      kind: "voice",
      title: "Thirty seconds, badly recorded",
      text: "",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-5",
      kind: "song",
      title: "Put this on tonight",
      text: "Harvest Moon",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "https://open.spotify.com/",
      songArtist: "Neil Young",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-6",
      kind: "illustration",
      title: "",
      text: "Six down. Halfway. Look up tonight — same moon, I checked.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "moon",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-7",
      kind: "memory",
      title: "The kitchen, February",
      text:
        "You'd been cooking for an hour and hadn't noticed it was raining through the window.\n\nI didn't say anything for a while because you were humming, and I wanted to keep it.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-8",
      kind: "photo",
      title: "Your handwriting on my shopping list",
      text: "I still have it. It says 'lemons (the good ones)'.",
      imageUrl: "https://images.pexels.com/photos/6003522/pexels-photo-6003522.jpeg?auto=compress&cs=tinysrgb&w=900",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-9",
      kind: "game",
      title: "Scratch this one",
      text: "",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "",
      scratchPrize: "I booked the coast house. The whole week, not the weekend.",
    },
    {
      id: "d-10",
      kind: "coupon",
      title: "",
      text: "One entire Sunday where we do absolutely nothing",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "star",
      couponTerms: "No plans. No phones. Non-transferable.",
      scratchPrize: "",
    },
    {
      id: "d-11",
      kind: "illustration",
      title: "",
      text: "One more sleep.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "sprig",
      couponTerms: "",
      scratchPrize: "",
    },
    {
      id: "d-12",
      kind: "letter",
      title: "Today",
      text:
        "You're reading this on the day, which means you did the whole thing — twelve mornings, in order, no skipping.\n\nI'll be at the door at seven. Don't tidy up.",
      imageUrl: "",
      audioUrl: "",
      videoUrl: "",
      songUrl: "",
      songArtist: "",
      attribution: "",
      illustration: "heart",
      couponTerms: "",
      scratchPrize: "",
    },
  ],
};
