import { openWhenContentSchema, type OpenWhenContent } from "./schema";

const img = (seed: string) => `https://picsum.photos/seed/kindloop-ow-${seed}/900/900`;

/** A date far enough out that the demo always shows a genuinely locked letter. */
const NEXT_YEAR = "2027-06-14T09:00";

/**
 * The public walkthrough at /demo/open-when.
 *
 * Every unlock method appears at least once, so the demo shows the whole idea:
 * some envelopes open now, some refuse, and the refusal is part of the gift.
 * Each one gets its own paper, ribbon, wax and handwriting — the box should look
 * like it was assembled over months, not generated.
 */
export const openWhenDemo: OpenWhenContent = openWhenContentSchema.parse({
  wood: "walnut",
  plate: "for Ana",
  boxTitle: "For the days that need it",
  dedication: "Don't read them all at once. That's the whole point.",

  letters: [
    {
      id: "ow-1",
      title: "Open when you're happy",
      paperStyle: "ivoryCotton",
      paperColor: "champagne",
      sealColor: "gold",
      sealIcon: "star",
      ribbon: "gold",
      hand: "elegant",
      ink: "sepia",
      lock: "none",
      greeting: "Oh good,",
      body: "If you've picked this one, something has gone right, and I want to be there for it even if I'm not.\n\nTell me about it later. Tell me the boring details too — the ones you think I won't care about. I will.",
      closing: "Proud of you,",
      signature: "S",
      photoUrl: img("happy"),
      photoCaption: "you, mid-laugh",
      surprise: "There's a fiver folded in the back of this box. Buy yourself the good coffee.",
    },
    {
      id: "ow-2",
      title: "Open when you miss me",
      paperStyle: "vintageBeige",
      paperColor: "softPink",
      sealColor: "burgundy",
      sealIcon: "heart",
      ribbon: "blush",
      hand: "romantic",
      ink: "burgundy",
      lock: "mood",
      mood: "missing you",
      greeting: "Hello you,",
      body: "I knew you'd reach for this one first.\n\nSit down for a second. I'm not as far away as it feels, and this exact hour will pass — it always does, even when it doesn't seem like it will.\n\nRead the next line twice.",
      closing: "Yours, still,",
      signature: "S",
      voiceUrl: "",
      surprise: "I miss you too. Constantly. Unglamorously.",
    },
    {
      id: "ow-3",
      title: "Open when you can't sleep",
      paperStyle: "darkElegant",
      paperColor: "classicWhite",
      sealColor: "navy",
      sealIcon: "infinity",
      ribbon: "navy",
      hand: "journal",
      ink: "navy",
      lock: "none",
      greeting: "It's late, isn't it.",
      body: "Don't try to fix anything tonight. Nothing decided at 3am has ever been worth keeping.\n\nHere's all you have to do: put this down, lie back, and breathe out longer than you breathe in. That's it. That's the whole instruction.\n\nI'll still be here in the morning.",
      closing: "Go to sleep,",
      signature: "S",
    },
    {
      id: "ow-4",
      title: "Open when you feel like giving up",
      paperStyle: "aged",
      paperColor: "warmBeige",
      sealColor: "emerald",
      sealIcon: "tree",
      ribbon: "forest",
      hand: "vintage",
      ink: "forest",
      lock: "password",
      password: "porto",
      passwordHint: "the city where you burned the rice",
      greeting: "Right. Listen.",
      body: "I've watched you do the hard thing more times than you remember, and every single time you thought you couldn't.\n\nYou are allowed to stop. You are allowed to rest. You are not allowed to believe you're incapable, because I have evidence, and the evidence is years long.",
      closing: "Still betting on you,",
      signature: "S",
      surprise: "Read the second paragraph again. Out loud this time.",
    },
    {
      id: "ow-5",
      title: "Open when you need a laugh",
      paperStyle: "linen",
      paperColor: "paleLavender",
      sealColor: "roseGold",
      sealIcon: "flower",
      ribbon: "plum",
      hand: "messy",
      ink: "purple",
      lock: "none",
      greeting: "Okay,",
      body: "Remember the extractor fan.\n\nThat's it. That's the whole letter. I'm not explaining it. If you're not laughing yet you will be in about four seconds.",
      closing: "You're welcome,",
      signature: "S",
      photoUrl: img("laugh"),
      photoCaption: "the fan, may it rest",
    },
    {
      id: "ow-6",
      title: "Open on your birthday",
      paperStyle: "deckled",
      paperColor: "cream",
      sealColor: "gold",
      sealIcon: "initials",
      ribbon: "cream",
      hand: "calligraphy",
      ink: "darkBrown",
      lock: "date",
      unlockAt: NEXT_YEAR,
      greeting: "Happy birthday,",
      body: "Another year of you, which is the outcome I was hoping for.\n\nI hope this one is gentler than the last. I hope you get the window seat. I hope somebody makes you a cake badly.",
      closing: "All my love,",
      signature: "S",
    },
    {
      id: "ow-7",
      title: "Open after we meet again",
      paperStyle: "washi",
      paperColor: "sage",
      sealColor: "black",
      sealIcon: "rose",
      ribbon: "sage",
      hand: "classic",
      ink: "black",
      lock: "creator",
      released: false,
      greeting: "So —",
      body: "You're back, or I am, and either way we've already had the conversation this letter was worried about.\n\nI'm leaving it sealed until then on purpose. Some things shouldn't be read early.",
      closing: "Told you,",
      signature: "S",
    },
    {
      id: "ow-8",
      title: "Open at the bench by the river",
      paperStyle: "watercolour",
      paperColor: "dustyBlue",
      sealColor: "ivory",
      sealIcon: "monogram",
      ribbon: "rust",
      hand: "elegant",
      ink: "navy",
      lock: "location",
      place: "the bench by the river",
      greeting: "You found it,",
      body: "If you're sitting where I think you're sitting, look slightly left of the third lamp post.\n\nThat's where I decided. I never told you that.",
      closing: "Same bench, always,",
      signature: "S",
    },
  ],
});
